Nc games 3 get api categories
JLaw96/be-nc-games-own pull request #2
Opened 2023-02-21 14:22 UTC by JLaw96

2023-02-21 14:31 UTC, pippaamy commented on __tests__/app.test.js
> +          });
Need a 404 test to test for /api/pathnotfound :)

2023-02-21 14:32 UTC, pippaamy commented on __tests__/app.test.js
> +            categories.forEach((category) => {
Need to check length of array before doing the forEach

2023-02-21 14:32 UTC, pippaamy requested changes
Good work! A couple of changes to make - then pop in another pull request :)

2023-02-22 10:49 UTC, Keb84 approved these changes
Looks good Johnny. Feel free to merge this now 👍

2023-02-22 10:50 UTC, merged